var users = {

    "abridger": {
        "login": "abridger",
        "id": 4664049,
        "avatar_url": "https://avatars.githubusercontent.com/u/4664049?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/abridger",
        "html_url": "https://github.com/abridger",
        "followers_url": "https://api.github.com/users/abridger/followers",
        "following_url": "https://api.github.com/users/abridger/following{/other_user}",
        "gists_url": "https://api.github.com/users/abridger/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/abridger/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/abridger/subscriptions",
        "organizations_url": "https://api.github.com/users/abridger/orgs",
        "repos_url": "https://api.github.com/users/abridger/repos",
        "events_url": "https://api.github.com/users/abridger/events{/privacy}",
        "received_events_url": "https://api.github.com/users/abridger/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Alan Bridger",
        "company": "",
        "blog": "http://www.critiqua.com",
        "location": "London, UK",
        "email": "alan@critiqua.com",
        "hireable": false,
        "bio": null,
        "public_repos": 31,
        "public_gists": 0,
        "followers": 17,
        "following": 18,
        "created_at": "2013-06-10T19:04:13Z",
        "updated_at": "2014-12-10T17:24:12Z"
    },

    "ejbyne": {
        "login": "ejbyne",
        "id": 8865177,
        "avatar_url": "https://avatars.githubusercontent.com/u/8865177?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ejbyne",
        "html_url": "https://github.com/ejbyne",
        "followers_url": "https://api.github.com/users/ejbyne/followers",
        "following_url": "https://api.github.com/users/ejbyne/following{/other_user}",
        "gists_url": "https://api.github.com/users/ejbyne/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ejbyne/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ejbyne/subscriptions",
        "organizations_url": "https://api.github.com/users/ejbyne/orgs",
        "repos_url": "https://api.github.com/users/ejbyne/repos",
        "events_url": "https://api.github.com/users/ejbyne/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ejbyne/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Edward Byne",
        "company": "",
        "blog": "",
        "location": "",
        "email": "",
        "hireable": false,
        "bio": null,
        "public_repos": 36,
        "public_gists": 0,
        "followers": 16,
        "following": 15,
        "created_at": "2014-09-22T18:42:12Z",
        "updated_at": "2014-12-10T17:24:12Z"
    }

}

module.exports = users;
